### ISSUE TITLE
Relative path in cwd didn't work in workspace mode

### ISSUE THREAD

**Issue by snys98** [nguyenngoclongdev/vs-terminal-keeper#10]
**Describe the bug**
Relative path in cwd didn't work in workspace mode.

**To Reproduce**
![image](https://github.com/nguyenngoclongdev/vs-terminal-keeper/assets/11873100/fb30cadd-1b29-44eb-8952-1fa6ba4c219f)

**Expected behavior**
terminal open in specified folder

**Platform:** 
Version: 1.85.1 (system setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
 - extension version: v1.1.14

**Comment by snys98** [comment]
sorry for the late reply, but I think my issue is different from what #3 mentioned.

relative path is working fine with normal folders, here this scenario is only for **vscode workspace**

![image](https://github.com/nguyenngoclongdev/vs-terminal-keeper/assets/11873100/3ab9ac62-2a30-4791-8405-1488cb450a3b)
![image](https://github.com/nguyenngoclongdev/vs-terminal-keeper/assets/11873100/edfcd93f-f932-42e5-96f1-82588a7c3a72)

**Comment by nguyenngoclongdev** [comment]
@snys98 Sorry for the late reply. I’ve been quite busy with work.
I’ve also recently returned to maintain the software I’ve released.

Regarding this issue, we’ve found the cause and fixed it in the latest version.
Here’s how to configure the "sessions" to work in your workspace:
```json
[
  {
    "name": "clients/admin",
    "cwd": "clients/admin", // 👉 At the workspace root, you can easy navigate to other directories in the workspace root
    "commands": [ "pwd" ]
  },
  {
    "name": "server/gateway",
    "cwd": "../server/gateway", // 👉 With the folder you add to the workspace, use '../' to move to the parent directory of the workspace root
    "commands": [ "pwd" ]
  },
  {
    "name": "server/modules",
    "cwd": "../server/modules", // 👉 With the folder you add to the workspace, use '../' to move to the parent directory of the workspace root
    "commands": [ "pwd" ]
  }
]
```

Let me know if you need more help! Thank you.
